LICENSE, assets/css/default.css, assets/css/input.css, build/build.py, build/deploy.sh, static/css/core.css
These code styling issues are reported on codefactor.io
=> 🎃 Fix some code styling issues

static/js/api.js
=> ⛳ fix date parsing error

static/js/core.js
This pull request resolves #11
=> 🕑 fix slow startup time

static/js/core.js
=> 🥃 userSettings: rename illegal key

static/js/api.js
This pull request resolves #21
=> 🧀 api.logout: fix cannot logout sometimes

static/css/core.css, static/js/api.js, static/js/core.js
This pull request resolves #23
=> 🎨 implement point grading in results screen

static/services/css/base.css, static/services/css/payask.css, static/services/js/script.js, static/services/payask.html
=> 🏓 Thêm trang chi tiết của dịch vụ payask

assets/js/belibrary.js, static/css/core.css, static/js/api.js, static/js/core.js
This pull request resolves #22
=> 🍣 Thêm tính năng xem danh sách lịch thi

assets/css/navbar.css, assets/css/smenu.css, assets/js/navbar.js, assets/js/smenu.js, static/css/core.css, static/js/core.js
This pull request resolves #32
=> 📐 add smenu left alignment

.gitignore, assets/js/scrollable.js, build/test.py
This pull request resolves #20
=> 🎯 scrollable: fix clamping thumb issue

assets/css/button.css, assets/css/default.css, assets/css/navbar.css, assets/css/smenu.css, assets/css/spinner.css, assets/css/wavec.css, assets/js/belibrary.js, assets/js/scrollable.js, static/css/core.css, static/js/api.js, static/js/core.js
This pull request resolves #27
=> 🍧 Thêm tính năng đăng kí/hủy đăng kí lớp tín chỉ

index.html, manifest.json, service-worker.js, static/js/core.js
=> 🧶 Installable PWA

.github/workflows/test.yml, assets/js/belibrary.js, static/css/core.css, static/css/dark.css, static/js/api.js, static/js/core.js
This pull request contains new look for `schedule` screen in list mode. This will need a revision in the future.
=> 🌄 `schedule`: redesign list schedule

assets/css/table.css, assets/js/belibrary.js, assets/js/smenu.js, metadata.json, static/css/core.css, static/css/dark.css, static/js/api.js, static/js/core.js
This pull request add a feature to automatically change to a working middleware is currently selected one errored on initialize or session check request. Lowest ping has the highest priority.
=> 🕋 Auto change middleware if current one is offline or errored

static/js/screens/results.js
add a function return array date of the semester
=> ✏ implement getScanDates()

.vscode/settings.json, static/js/screens/results.js
update function  getscandate of semester 2
=> 🏗 Update `getScanDates()`

static/js/screens/results.js
getscandate update semester =3 was be missed bacause conflix error
=> 🧭 getscandate update semester was be missed bacause conflix error

.vscode/settings.json, static/js/api.js
Rounding point before calculating the average
=> 🍔 Round subject's point before calculating average point

static/js/screens/results.js
Fix GPA point not printing correctly
=> ✏ Fix GPA point not rounding correctly for each subject

.github/workflows/test.yml, static/js/api.js, static/js/core.js, static/js/screens/schedule.js
=> 🧇 Hiển thị cảnh báo nợ học phí trong trang xem lịch học

metadata.json, static/css/core.css, static/js/api.js, static/js/core.js, static/js/screens/results.js
This PR resolves #69, which added a new server switcher options and add support for CTMS4KINHTE page.
Most of the changes focus on `api.results()`, because their result page have much more information than normal, which does make some initial calculation easier (kind of).
Most of the featues are functional, but more testing will be required as we don't know what else is different. Also testing for this server is limited because I don't have an account on this server.
=> 🚀 Implement server switching and add support for CTMS4KINHTE
